name: Deploy to QA

on:
  push:
    branches:
      - release

jobs:
  deploy-to-qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Build Docker Image
        run: docker build -t ecomarket-app-backend-springboot:qa .

      - name: Save Docker Image to Tar File
        run: docker save ecomarket-app-backend-springboot:qa -o ecomarket-app-backend-springboot-qa.tar

      - name: Copy Docker Image to QA Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.QA_SERVER_HOST }}
          username: ${{ secrets.QA_SERVER_USER }}
          key: ${{ secrets.QA_SERVER_SSH_KEY }}
          port: ${{ secrets.QA_SERVER_PORT }}
          source: "ecomarket-app-backend-springboot-qa.tar"
          target: "/tmp/ecomarket-app-backend-springboot-qa.tar"

      - name: Load Docker Image and Run Container on QA Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.QA_SERVER_HOST }}
          username: ${{ secrets.QA_SERVER_USER }}
          key: ${{ secrets.QA_SERVER_SSH_KEY }}
          port: ${{ secrets.QA_SERVER_PORT }}
          script: |
            docker load -i /tmp/ecomarket-app-backend-springboot-qa.tar
            docker stop ecomarket-app-backend-springboot-qa || true
            docker rm ecomarket-app-backend-springboot-qa || true
            docker run -d --name ecomarket-app-backend-springboot-qa -p 8080:8080 ecomarket-app-backend-springboot:qa
